mutation DeleteNoteSoft($id: UUID!, $deletedAt: Datetime!) {
    updateNotesCollection(
        set: { deletedAt: $deletedAt }
        filter: { id: { eq: $id } }
        atMost: 1
    ) {
        records {
            id
            title
            body
            createdAt
            updatedAt
            deletedAt
        }
    }
}