query GetActiveNotes {
  notesCollection(
    filter: { deletedAt: { is: NULL }}
    orderBy: [{ createdAt: DescNullsLast }]) {
    edges {
      node {
        id
        title
        body
        createdAt
        updatedAt
        deletedAt
      }
    }
  }
}


